### ISSUE TITLE
Redo Sprig gallery/gameplay experience

### ISSUE THREAD

**Issue by recursiveforte** [hackclub/sprig#1937]
I propose we separate the editor from the experience of playing a game. When opening a game, we should only show the game and its description/author/metadata - there should be a button to open the editor interface, which includes the code and help panes. This helps turn Sprig into more of a "game platform" instead of a platform purely focused on creating games, drawing people in who would not otherwise play games in the gallery.

The former interface - focused on gameplay - should show the game as the largest element and have the following functions:
- a share button
- a button to open the code editor
- a button to upload the game to the console
- a description (determined by the text in the first comment block, after the metadata).
- information on the submitted date, author, # of views, and an upvote function

```[tasklist]
### Tasks
- [ ] #1947
- [ ] https://github.com/hackclub/sprig/issues/1948
- [ ] https://github.com/hackclub/sprig/issues/1949
- [ ] https://github.com/hackclub/sprig/issues/1951
```

**Comment by grymmy** [comment]
I approve these generally but please create individual feature requests per bullet item and add any required product info to each for their impl

**Comment by grymmy** [comment]
I am closing this issue as the actual work behind it is logged as separate issues.
